http_port 3128

acl allow_localnet dst 10.218.20.0/24
acl allowed_domains dstdomain generativelanguage.googleapis.com
http_access allow allow_localnet
http_access allow allowed_domains

http_access deny all

cache_dir ufs /var/spool/squid 100 16 256
coredump_dir /var/spool/squid
